### ISSUE TITLE
An Introduction?

### ISSUE THREAD

**Issue by aseaday** [kemingy/gathers#6]
I am very interested in this project because I am developing a cached service for translation.
Could you gimme an introduction of this project. Is it a library for use in your vectorchord?

**Comment by kemingy** [comment]
Sure.

This library will try to explore several widely used k-means variants, including the new RaBitQ (used for assigning vec to the nearest cluster). And it will provide both Rust & Python APIs. This will be used in vectorchord as an external (or call it remote) index-building component.

I'll update the README and write a blog (tracked in https://github.com/tensorchord/VectorChord/issues/111) later.

**Comment by kemingy** [comment]
Check the blog: https://blog.pgvecto.rs/benefits-and-steps-of-external-centroids-building-in-vectorchord
